#!groovy

// Generated by IBM TransformationAdvisor
// Thu Mar 14 16:11:31 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}