#!groovy

// Generated by IBM TransformationAdvisor
// Tue Mar 05 20:35:29 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}