#!groovy

// Generated by IBM TransformationAdvisor
// Mon Apr 01 13:32:37 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}